--!strict
return table.freeze({
	Image = "rbxassetid://75739693637093",
	MinX = -1150, MinZ = -3700, Width = 2200, Height = 4400,
	Spans = table.freeze({700, 1400, 4400}),
	UpdateInterval = 0.1,
	Landmarks = {
		{label = "Szkieł • policjant", icon = "P", x = 374.666, z = 28.805, kind = "police"},
		{label = "Punkt startowy", icon = "S", x = 301.3, z = 37.2, kind = "spawn"},
		{label = "Sklep", icon = "$", x = 100.8, z = -229.2, kind = "shop"},
		{label = "Sklep", icon = "$", x = 212.5, z = -2976, kind = "shop"},
		{label = "Sklep", icon = "$", x = 468.685, z = -640.399, kind = "shop"},
		{label = "Remiza OSP Makowice", icon = "R", x = -42.11, z = -3361.41, kind = "fire"},
	},
	QuestPoints = {
		{id = "BusStopd1", x = 70.8784, z = -496.4596},
		{id = "BusStopd2", x = 13.9777, z = -2954.1514},
		{id = "BusStopd3", x = -191.1529, z = 95.8533},
	},
})
